# Generated by Django 4.2.13 on 2024-08-31 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userresponse',
            name='unique_user_response',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='play_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together={('user', 'question')},
        ),
    ]
