# Generated by Django 4.2.13 on 2024-08-31 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_remove_userresponse_unique_user_response_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together=set(),
        ),
    ]
